version: 2

sources:

  - name: uwinnipeg
    description: "Class test data"
    database: GAHIR_AI2024
    schema: CLASS_TEST
    tables:
      - name: CUSTOMERS
        description: "this is the Customer table info"
      - name: ORDERS
        description: "this is orders table info"
      - name: PRODUCT
        description: "This ia a product table info"
